package it.polimi.ingsw.network;

public enum Content {
    //s->c
    LOGIN_REQUEST,
    NUM_PLAYERS_REQUEST,
    ASKTYPERESOURCE,
    ASK_RESOURCE_PLACEMENT,
    START_GAME,
    DEAL_LEADERCARDS,
    DEVCARD_BOUGHT,


    GENERIC_MESSAGE,

    //c->s
    LOGIN,
    LOGIN_DATA,
    PLAYERS_NUMBER,
    RESOURCE_TYPE,
    RESOURCE_PLACEMENT,
    DISCARD_LEADER,


    LOGIN_SUCCESSFUL,
    INVALID_DATA,

    RESPONSE,

    ACTIVATE_LEADER,
    LEADER_ACTIVATED,
    GAME_STATE,
    DONE_ACTION,
    GOING_MARKET,
    SELECT_LINE,
    SEND_RESOURCE,
    DISCARD_RES,
    MOVE_RES,
    STORE_RES,
    POSITIVE,
    ACTIVATE_PRODUCTION,

}

