package it.polimi.ingsw.network;

public enum Contents {
    LOGIN_REQUEST, LOGIN_DATA, LOGIN_SUCCESSFUL, START_GAME, RESPONSE, DISCARD_LEADER,
    ACTIVATE_LEADER, LEADER_ACTIVATED, GAME_STATE, DONE_ACTION, GOING_MARKET, SELECT_LINE,
    SEND_RESOURCE, DISCARD_RES, MOVE_RES, STORE_RES, POSITIVE, ACTIVATE_PRODUCTION, INPUT_RESOURCE
}
