package it.polimi.ingsw.network;

public enum Content {
    //s->c
    LOGIN_REQUEST,
    ASKTYPERESOURCE,
    ASK_RESOURCE_PLACEMENT,
    ASK_RESOURCE_PLACEMENT_OR_DISCARD,
    ASK_SWAP_WHITE,
    DISPLAY_LEADERCARDS,
    ASK_ACTION,
    ASK_DONE,
    ASK_PLAYLEADER,

    NORESOURCE_AVAILABLE,
    TURN_FAVORTILE,

    DISPLAY_SLOTS,
    DISPLAY_DEVCARDS,
    DISPLAY_FAITHTRACK,
    DISPLAY_WAREHOUSE,
    DISPLAY_MARKET,
    DISPLAY_PERSONALBOARD,

    END_GAME,
    GENERIC_MESSAGE,
    GENERIC_POPUP,

    //c->s
    LOGIN_DATA,
    RESOURCE_TYPE,
    RESOURCE_PLACEMENT,
    SWAPPED_RESOURCE,
    DISCARD_LEADER,
    DISCARDED_LEADER,
    ACTIVATE_LEADER,
    GOING_MARKET,
    ACTIVATE_PRODUCTION,
    BUY_DEVCARD,
    DONE_ACTION,




}

